// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Canopy.Mobile")>]
[<assembly: AssemblyProductAttribute("Canopy.Mobile")>]
[<assembly: AssemblyDescriptionAttribute("Canopy testing framework for mobile apps.")>]
[<assembly: AssemblyVersionAttribute("1.6.4")>]
[<assembly: AssemblyFileVersionAttribute("1.6.4")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Canopy.Mobile"
    let [<Literal>] AssemblyProduct = "Canopy.Mobile"
    let [<Literal>] AssemblyDescription = "Canopy testing framework for mobile apps."
    let [<Literal>] AssemblyVersion = "1.6.4"
    let [<Literal>] AssemblyFileVersion = "1.6.4"
    let [<Literal>] AssemblyConfiguration = "Release"
